### ISSUE TITLE
Wrong font name

### ISSUE THREAD

**Issue by saneef** [wentin/typedetail#1]
In the page about [San Francisco](http://typedetail.com/san-francisco.html), in the similar typefaces list I think, you by mistake wrote Arial instead of Helvetica (or the font sample picked Helvetic instead of Arial) ;)

![screen shot 2015-05-27 at 15 40 25](https://cloud.githubusercontent.com/assets/81863/7833746/cd2c2b5a-0486-11e5-8ea1-dc6b4b48472a.png)

**Comment by wentin** [comment]
yeah, I first pick Arial because I don't have helvetica web font, and helvetica is web safe for MAC but not windows. I fixed it
