### ISSUE TITLE
Font’s License

### ISSUE THREAD

**Issue by moyogo** [wentin/typedetail#6]
Sorry to be the party pooper but I doubt you have the right license for some of the fonts, particularly San Francisco Text, San Francisco Display or Bookerly. The San Francisco fonts are licensed by Apple and Bookerly by Amazon. So unless they have given their permission for this, you shouldn’t use those fonts.

**Comment by davelab6** [comment]
It's just an image, not the actual fonts, right? Assuming the contributor
owns a iwatch or kindle, they can legally generate such an image, right?

**Comment by wentin** [comment]
It is a grey area. It is closer to journalism, rather than using it for one's own purpose. The annotation page is closer to a news article introducing the font and its feature, and news articles have no issue embed the font specimen in the article webpage. Type detail didn't use these fonts to display any of its own text copies, only the specimen.

**Comment by moyogo** [comment]
@davelab6 at the moment they are webfont files, generated via Fontsquirrel, hosted at nicholastodor.com, typedetail.com or in the source tree (effectively redistributing).

@wentin It’s not a grey area. Images obtained from people who have a licence would be fine, i.e. a screenshot would probably be fine.
What you’re doing is akin to attaching a modified copy of Windows that runs in a virtual machine in the browser to a press article about Windows, when the license doesn’t allow that.

**Comment by davelab6** [comment]
Oh yeah this is really bad. You need to make svg images of the letters
pronto

**Comment by wentin** [comment]
The idea of type detail is to promote and praise type designer's great effort and amazing work product, not to take advantage of it or redistributing unlicensed font in any way. For that I apologized. All unlicensed font file has been taken down.
